Repository MuxammilSidd/FAST-KHI-Semester-3, pull requests merged in 2024-12, with the labels that each got.

#1 added FOM
  Fundamentals of Management/test.txt
Labels: good first issue

#3 Added FOA
  Fundamentals of Accounting/Test.txt
Labels: good first issue

#4 Added FOA Material
  Fundamentals of Accounting/FOA Course Outline Fall'24.pdf
  Fundamentals of Accounting/Test.txt
Labels: enhancement, good first issue

#5 Added Quizzes in Quiz Folder
  Fundamentals of Accounting/Quiz/BSCS - 3B Quiz 1 Solution.pdf
  Fundamentals of Accounting/Quiz/BSCS - 3B Quiz 1.pdf
  Fundamentals of Accounting/Quiz/BSCS - 3B Quiz 2 Solution.pdf
  Fundamentals of Accounting/Quiz/BSCS - 3B Quiz 2.pdf
Labels: enhancement
